/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  checkers: ['typescript'],
  concurrency: 2,
  coverageAnalysis: 'perTest',
  disableTypeChecks: false,
  incremental: true,
  incrementalFile: 'reports/stryker-web-incremental.json',
  // Bound worker lifetime after reproducible Node 24/V8 crashes in long Jest runs.
  maxTestRunnerReuse: 100,
  ignorePatterns: [
    'android',
    'ios',
    'design',
    'dist',
    'builds',
    'coverage',
    'apps/web/.next',
    'apps/web/playwright-report',
    'apps/web/test-results',
  ],
  jest: {
    configFile: 'apps/web/jest.config.mjs',
    enableFindRelatedTests: true,
    projectType: 'custom',
  },
  mutate: [
    'apps/web/src/lib/auth/navigation.ts',
    'apps/web/src/app/auth/callback/route.ts',
    'apps/web/src/lib/auth/session.ts',
    'apps/web/src/lib/supabase/proxy.ts',
    'apps/web/src/proxy.ts',
    'apps/web/src/features/review/actions.ts',
    'apps/web/src/features/review/correction-validation.ts',
    'apps/web/src/features/review/correction-client.ts',
    'apps/web/src/features/review/correction-actions.ts',
    'apps/web/src/features/review/correction-refresh.ts',
    'apps/web/src/features/review/session-corrections.ts',
    'apps/web/src/features/words/actions.ts',
    'apps/web/src/features/analysis/word-persistence.ts',
    'packages/domain/src/srs.ts',
    'apps/web/src/features/analysis/analysis-preview.ts',
    'apps/web/src/features/analysis/semantic-duplicate.ts',
    'apps/web/src/features/collections/collection-validation.ts',
    'apps/web/src/features/search/word-search.ts',
    'apps/web/src/features/settings/account-deletion.ts',
    'apps/web/src/features/words/word-image.ts',
    'apps/web/src/features/words/word-mutations.ts',
  ],
  reporters: ['clear-text', 'progress', 'html', 'json'],
  testRunner: 'jest',
  thresholds: {
    break: 90,
    high: 90,
    low: 75,
  },
  timeoutMS: 15_000,
  tsconfigFile: 'apps/web/tsconfig.stryker.json',
  typescriptChecker: {
    prioritizePerformanceOverAccuracy: true,
  },
}

export default config
