import { StyleSheet } from 'react-native'
import { Colors } from '@/constants/Colors'

export const reviewInsightsStyles = StyleSheet.create({
  summary: { gap: 16 },
  title: { fontSize: 26, fontWeight: '700', lineHeight: 34 },
  subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4 },
  staleBanner: { borderRadius: 14, padding: 14 },
  staleTitle: { fontSize: 15, fontWeight: '700' },
  staleCopy: { fontSize: 14, lineHeight: 20, marginTop: 2 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metric: {
    flexGrow: 1,
    flexBasis: '46%',
    minHeight: 92,
    borderRadius: 14,
    padding: 14,
    justifyContent: 'center',
  },
  metricValue: { fontSize: 28, fontWeight: '700' },
  metricLabel: { fontSize: 14, lineHeight: 20, marginTop: 2 },
  definition: { fontSize: 13, lineHeight: 19 },
  section: { borderRadius: 16, padding: 16 },
  sectionTitle: { fontSize: 19, fontWeight: '700', lineHeight: 25 },
  sectionSubtitle: { fontSize: 13, lineHeight: 19, marginTop: 4 },
  bars: { gap: 10, marginTop: 14 },
  barRow: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  barLabel: { width: 82, fontSize: 12 },
  distributionLabel: { width: 116, fontSize: 12 },
  barTrack: {
    flex: 1,
    height: 10,
    borderRadius: 5,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: 5 },
  barCount: {
    width: 28,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  forecastFootnote: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginTop: 12,
  },
  footnote: { fontSize: 13 },
  primaryButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 14,
  },
  primaryButtonText: {
    color: Colors.legacy.white,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  noDifficultWords: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 14,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyCopy: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 8,
  },
  secondaryButton: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    marginTop: 20,
  },
  secondaryButtonText: { fontSize: 15, fontWeight: '600' },
})
