import { StyleSheet, Dimensions } from 'react-native'
import { Colors } from '@/constants/Colors'

const { height: screenHeight } = Dimensions.get('window')

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.transparent.modalOverlay,
    zIndex: 1000,
  },
  container: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
    height: screenHeight * 0.8, // 80% of screen from bottom
  },
  dragIndicator: {
    width: 36,
    height: 4,
    backgroundColor: Colors.neutral[300],
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 4,
    zIndex: 3,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  wordTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginRight: 8,
  },
  articleText: {
    fontSize: 18,
    fontStyle: 'italic',
    opacity: 0.7,
  },
  closeButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: Colors.neutral[100],
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 96,
  },
  imageContainer: {
    alignItems: 'center',
    marginVertical: 20,
    position: 'relative',
  },
  imageLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.neutral[100],
    borderRadius: 12,
  },
  image: {
    width: 250,
    height: 250,
    borderRadius: 12,
    backgroundColor: Colors.neutral[100],
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  translationsContainer: {
    gap: 8,
  },
  translationItem: {
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary.DEFAULT,
  },
  translationText: {
    fontSize: 16,
    lineHeight: 22,
  },
  translationTextRussian: {
    fontSize: 16,
    lineHeight: 22,
    fontStyle: 'italic',
    opacity: 0.7,
  },
  partOfSpeechText: {
    fontSize: 16,
    color: Colors.neutral[600],
    backgroundColor: Colors.neutral[100],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
  },
  examplesContainer: {
    gap: 12,
  },
  exampleItem: {
    backgroundColor: Colors.neutral[50],
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary.DEFAULT,
  },
  exampleDutch: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.neutral[900],
    marginBottom: 4,
  },
  exampleEnglish: {
    fontSize: 14,
    color: Colors.neutral[600],
    lineHeight: 20,
  },
  exampleRussian: {
    fontSize: 14,
    color: Colors.neutral[600],
    lineHeight: 20,
    fontStyle: 'italic',
    marginTop: 4,
  },
  progressContainer: {
    gap: 8,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
  },
  progressText: {
    fontSize: 14,
    opacity: 0.7,
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '500',
  },
  noExamplesText: {
    fontSize: 14,
    color: Colors.neutral[600],
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 20,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.transparent.modalOverlay,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  reviewBadge: {
    backgroundColor: Colors.warning.light,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  reviewText: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.warning.DEFAULT,
  },
})
