appId: ${APP_ID}
---
- assertVisible: Select a better image.*
- assertVisible: Load More Images
- tapOn:
    point: 74%, 34%
- extendedWaitUntil:
    notVisible: Select a better image.*
    timeout: 15000
- assertVisible:
    id: modal-close-button
