appId: ${APP_ID}
---
- launchApp
- runFlow:
    when:
      visible: Back
    commands:
      - tapOn: Back
- tapOn: Settings
- extendedWaitUntil:
    visible:
      id: screen-settings
    timeout: 15000
- scrollUntilVisible:
    element:
      id: force-sync-button
    direction: DOWN
    timeout: 20000
- tapOn:
    id: force-sync-button
- waitForAnimationToEnd:
    timeout: 5000
- extendedWaitUntil:
    visible: '.*[0-9]+ pending.*'
    timeout: 15000
- assertNotVisible: Up to date
