appId: ${APP_ID}
---
- launchApp:
    clearState: false
- runFlow:
    when:
      visible: "System UI isn't responding"
    commands:
      - tapOn: Wait
- openLink: dutchlearning://share/13876e09-23c7-4ed7-8017-b7ee2580d73c
- extendedWaitUntil:
    visible: D10 Synthetic Shared
    timeout: 30000
- assertVisible: '.*zeil.*'
- assertVisible: '.*getij.*'
- assertNotVisible: d10-unshared-secret
- assertVisible: '2 of 2 words selected.*'
- tapOn:
    id: import-target-820e9bad-4fc8-40ea-bcd6-216b86f2007c
- tapOn:
    id: import-selected-words-button
- extendedWaitUntil:
    visible:
      id: screen-collections
    timeout: 30000
