import assert from 'node:assert/strict'
import test from 'node:test'
import { createClient } from '@supabase/supabase-js'
import { fetchAllRows } from '../../apps/web/src/lib/supabase/fetch-all-rows.ts'
import {
  startFixtureBackend,
  createFixture,
  snapshot,
  PUBLIC_KEY,
  USER_ID,
} from './fixture-backend.mjs'

test('snapshot and actual paginated client reads have identical fixture data at boundaries', async t => {
  const backend = await startFixtureBackend()
  t.after(() => backend.close())
  const client = createClient(backend.url, PUBLIC_KEY, {
    auth: { persistSession: false },
  })
  for (const [words, events] of [
    [500, 0],
    [2500, 501],
    [5000, 5000],
  ]) {
    const fixture = createFixture({ words, events, selected: 20 })
    const expected = snapshot(fixture)
    backend.configure(fixture, 'snapshot', 'snapshot')
    const rpc = await client.rpc('get_web_review_snapshot_v1')
    assert.equal(rpc.error, null)
    assert.deepEqual(rpc.data, expected)
    backend.configure(fixture, 'legacy', 'legacy')
    const missing = await client.rpc('get_web_review_snapshot_v1')
    assert.equal(missing.error.code, 'PGRST202')
    for (const [table, field, maxRows] of [
      ['words', 'words', Infinity],
      ['effective_review_events', 'events', 5000],
    ]) {
      const columns = Object.keys(
        expected[field][0] ?? {
          answered_correctly: null,
          assessment: null,
          event_id: null,
          review_mode: null,
          reviewed_at: null,
          word_id: null,
        }
      ).join(',')
      const result = await fetchAllRows(
        (from, to) => {
          const query = client
            .from(table)
            .select(columns)
            .eq('user_id', USER_ID)
            .range(from, to)
          return table === 'words' ? query.is('deleted_at', null) : query
        },
        { maxRows }
      )
      assert.equal(result.error, null)
      assert.deepEqual(result.data, expected[field])
      const count = expected[field].length
      const pages =
        count === maxRows ? count / 500 : Math.floor(count / 500) + 1
      assert.equal(
        backend.requests.filter(request => request.path.endsWith(`/${table}`))
          .length,
        pages
      )
    }
    assert.equal(
      fixture.words.filter(word => word.next_review_date === '2020-01-01')
        .length,
      20
    )
    assert.equal(backend.errors.length, 0)
  }
})

test('fixture backend rejects unscoped reads, unknown RPCs and table writes', async t => {
  const backend = await startFixtureBackend()
  t.after(() => backend.close())
  const client = createClient(backend.url, PUBLIC_KEY, {
    auth: { persistSession: false },
  })
  const unscoped = await client.from('words').select('word_id')
  assert.ok(unscoped.error)
  const write = await client.from('words').insert({ dutch_lemma: 'blocked' })
  assert.ok(write.error)
  const unknown = await client.rpc('unknown_rpc')
  assert.ok(unknown.error)
  assert.equal(backend.errors.length, 3)
  assert.ok(backend.requests.every(request => request.status === 500))
})

test('fixture auth cookies are generated by the installed SSR client', async t => {
  const backend = await startFixtureBackend()
  t.after(() => backend.close())
  const cookies = await backend.cookies('http://127.0.0.1:3000')
  assert.ok(cookies.length > 0)
  assert.ok(
    cookies.every(
      cookie => cookie.name.startsWith('sb-') && cookie.value.length > 0
    )
  )
  assert.equal(backend.errors.length, 0)
})
