#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting and formatting
npx lint-staged

# Check for constants changes and warn about deployment
.husky/check-constants

# Check for high cognitive complexity
.husky/check-complexity